Prevent NullPointerException when caret is not present on text component
Observed exception:

java.lang.NullPointerException: Cannot invoke "javax.swing.text.Caret.getDot()" because "this.caret" is null
            at java.desktop/javax.swing.text.JTextComponent.getCaretPosition(JTextComponent.java:1704)
            at org.netbeans.modules.lsp.client.bindings.MarkOccurrences.<init>(MarkOccurrences.java:71)
            at org.netbeans.modules.lsp.client.bindings.TextDocumentSyncServerCapabilityHandler.lambda$registerBackgroundTasks$6(TextDocumentSyncServerCapabilityHandler.java:330)
            at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
            at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
            at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
            at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
            at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
            at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
            at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
            at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
            at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
            at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
            at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
            at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
            at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)