fix NPEs in UI code during commit validation tests.
example:
 java.lang.NullPointerException: Cannot invoke
   "java.awt.Component.getBackground()" because the return value of
   "javax.swing.JViewport.getView()" is null