java.source.base: Fix for Java 11, update args, swap import
Fixes the following issues

src/org/netbeans/api/java/source/SourceUtils.java:427:
error: constructor NamedImportScope in class NamedImportScope cannot be
applied to given types;
                NamedImportScope importScope = new
NamedImportScope(unit.packge, unit.toplevelScope);
                                               ^
  required: Symbol
  found: PackageSymbol,WriteableScope
  reason: actual and formal argument lists differ in length

src/org/netbeans/modules/java/source/NoJavacHelper.java:69:
error: cannot find symbol

unsafe.defineClass("com.sun.tools.javac.code.Scope$WriteableScope",
classData, 0, classData.length, scopeClass.getClassLoader(),
scopeClass.getProtectionDomain());
                          ^
  symbol:   method
defineClass(String,byte[],int,int,ClassLoader,ProtectionDomain)
  location: variable unsafe of type Unsafe