Don't raise user visible warning if declarative MIMERegistration can't be parsed
After beea5ce (LSP/Textmate: Implement multiview support for
generic/textmate based syntax support) it was observed, that
occasionally an IllegalArgumentException was raised from the
MimeResolverImpl (see full stacktrace below). 

The error message indicates that the description file is not valid
anymore. This matches the renewal of the registration at startup.

Log this on info level, so that is not raised to users attention, as
for the LSP case, the updated file is available milliseconds later and
should regenerate the resolvers in the next iteration.


java.lang.IllegalArgumentException: MultiFileObject@d1d4bdb[Services/MIMEResolver/c.xml] parent: MultiFileObject@27ddc920[Services/MIMEResolver] validFlag: false validRoot: MultiFileObject@49354fe[root of SystemFileSystem[org.netbeans.core.startup.layers.SystemFileSystem@20cea7a4]] isValidRoot: true
                at org.netbeans.modules.openide.filesystems.declmime.MIMEResolverImpl.create(MIMEResolverImpl.java:344)
                at org.netbeans.modules.openide.filesystems.declmime.MIMEResolverImpl.forDescriptor(MIMEResolverImpl.java:67)
                at org.openide.filesystems.MIMESupport$CachedFileObject.declarativeResolvers(MIMESupport.java:256)
                at org.openide.filesystems.MIMESupport$CachedFileObject.getResolvers(MIMESupport.java:197)
                at org.openide.filesystems.MIMESupport$CachedFileObject.resolveMIME(MIMESupport.java:340)
                at org.openide.filesystems.MIMESupport$CachedFileObject.getMIMEType(MIMESupport.java:287)
                at org.openide.filesystems.MIMESupport.findMIMEType(MIMESupport.java:111)
                at org.openide.filesystems.FileUtil.getMIMEType(FileUtil.java:1388)
                at org.openide.filesystems.FileObject.getMIMEType(FileObject.java:642)
                at org.openide.filesystems.AbstractFileObject.getMIMEType(AbstractFileObject.java:169)
                at org.openide.filesystems.MultiFileObject.getMIMEType(MultiFileObject.java:623)
                at org.openide.filesystems.MultiFileObject.getMIMEType(MultiFileObject.java:623)
                at org.openide.loaders.DataLoaderPool.allLoaders(DataLoaderPool.java:307)
                at org.openide.loaders.DataLoaderPool.findDataObject(DataLoaderPool.java:505)
[catch] at org.openide.loaders.FolderList.createBoth(FolderList.java:743)
                at org.openide.loaders.FolderList.getObjects(FolderList.java:539)
                at org.openide.loaders.FolderList.access$600(FolderList.java:52)
                at org.openide.loaders.FolderList$ListTask.computeResult(FolderList.java:938)
                at org.openide.loaders.FolderList$ListTask.run(FolderList.java:914)
                at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1403)
                at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
                at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
                at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2018)