Update validator.jar for html.validation
6debf7f90cf42e7dcac649cc6d55abf38ab678cc updated the validator.jar, this
update was missing the removal of the CSS validator, which caused
NoClassDefFoundError at runtime:

java.lang.NoClassDefFoundError: org/w3c/css/util/ApplContext
at nu.validator.datatype.MediaQuery.checkValid(MediaQuery.java:47)
at nu.validator.datatype.AbstractDatatype.checkValid(AbstractDatatype.java:77)
at com.thaiopensource.relaxng.impl.DataDataDerivType.dataDeriv(Unknown Source)
at com.thaiopensource.relaxng.impl.PatternMemo.dataDeriv(Unknown Source)
at com.thaiopensource.relaxng.impl.PatternValidator.startElement(Unknown Source)

This changeset updates the validator patch by removing the code for the
css validator.

In addition the libararies were updated to better match the libraries
html validator expects.