NETBEANS-5775: NoSuchMethodError: 'void com.sun.tools.javac.util.Log.<init>in .dump files when running NetBeans with JDK17+26
Since the code uses the same DEV_NULL for all the PrintWriters, replace the removed Log constructor taking 3 PrintWriters with the one that takes just one PrintWriter and use it for all outputs, that constructor exists from JDK 8 til JDK17+26/JDK18+1.