Fix and simplify handling of JSPParser classloader
The classloader was reset after each invocation by calls to
resetClassLoaders, so there is already little caching present here.

The old behavior though posed a different problem: the classloaders
were shared into multiple threads and calls to resetClassLoaders were
not coordinated, so the "slower" thread could be faced with a closed
classloader. For an URLClassLoader this means, that classes already
loaded work, new classes can't be loaded. This leads to difficult to
debug situations.

At runtime this was observed as:

Unable to read TLD "META-INF/liferay-portlet-ext.tld" from JAR file
"file:/home/matthias/.m2/repository/com/liferay/portal/release.portal.api/7.4.3.94-ga94/release.portal.api-7.4.3.94-ga94.jar":
org.apache.jasper.JasperException: PWC6112: Failed to load or
instantiate TagExtraInfo class: com.liferay.taglib.portlet.ActionURLTei