stabilize unreliable tests for smoother CI operation.
wrap platform/core.windows, favorites and settings into retry script.

mitigates the following exception which causes the tests to be very
unreliable in CI:
java.lang.AssertionError: Should have found a nonproblematic provider
of needs org.openide.modules.jre.JavaFX among [...]

Separate reliable from unreliable PHP tests and wrap unreliable tests
in retry script.