Enterprise: Fix multiple places where null values could be encountered and are not protected
Observed exception:

java.lang.NullPointerException: Cannot invoke "org.netbeans.api.j2ee.core.Profile.isAtMost(org.netbeans.api.j2ee.core.Profile)" because "profile" is null
    at org.netbeans.modules.websvc.rest.editor.AsyncConverter.isApplicable(AsyncConverter.java:98)
    at org.netbeans.modules.websvc.rest.editor.AsyncConverterTask.run(AsyncConverterTask.java:61)
    at org.netbeans.modules.websvc.rest.editor.AsyncConverterTask.run(AsyncConverterTask.java:52)
[catch] at org.netbeans.modules.java.source.JavaSourceAccessor$CancelableTaskWrapper.run(JavaSourceAccessor.java:273)
    at org.netbeans.modules.parsing.impl.TaskProcessor.callParserResultTask(TaskProcessor.java:561)
    at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:786)
    at org.openide.util.lookup.Lookups.executeWith(Lookups.java:288)
    at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:702)
    at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:663)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
    at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1403)
    at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
    at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
    at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2018)